---
title: "Projects"
---

# Projects

## EPI Capstone Course: Improved Drinking Water Sources and Diarrheal Cases

This research project explores the association between primary drinking water sources and diarrheal prevalence in East Hararghe, Ethiopia. Using a cross-sectional survey of 977 households, the study found that improved water sources significantly reduce the odds of diarrhea. The findings emphasize the importance of integrated WASH interventions to improve public health outcomes.

I used R to clean the data, create descriptive tables, calculate measures of association, and conduct logistic regression analysis in this research project.

[View Project Materials](https://www.care.org/our-work/food-and-nutrition/water/)

---

## Public Health Data Visualization Project：Cardiovascular Disease

This project analysis identifies key risk factors associated with heart disease using statistical modeling and data visualization in R. By examining demographic and health metrics, the report provides insights into prevalence patterns, aiming to enhance predictive accuracy and support clinical decision-making for cardiovascular health management.

[View GitHub Repository](https://github.com/Sliu639/Finalproject4)

---

## Applied Practice Experience: Medical Device Performance Summary

For my Applied Practice Experience, I summarized clinical and preclinical performance information for a medical insufflator. This work involved reviewing device-related information and organizing findings related to safety, effectiveness, and usability. The goal of this project was to translate technical information into a clear summary that could support professional communication and decision-making.

[View Project Materials](https://www.smartsurgn.com/products)
